### ISSUE TITLE
YAML Build Definition Usage Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by smokedlinq** [almtcger/VstsExtensions#7]
I am trying to use the YAML build definition with this task and I receive an error: Cannot read property 'Symbol(Symbol.iterator)' of undefined

I used the YAML generated from a previous definition, the task step is this:

### Build Definition
```yaml
- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@3
        displayName: Build Quality Gate
        inputs:
          checkCoverage: true
          coverageFailOption: fixed
          coverageThreshold: 80
```

### Build Output
```
******************************************************************************
Starting: Build Quality Gate
******************************************************************************
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 3.0.1
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/almtcger/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Cannot read property 'Symbol(Symbol.iterator)' of undefined
At least one build quality policy was violated. See Build Quality Checks section for more details.
******************************************************************************
Finishing: Build Quality Gate
******************************************************************************
```

The full build definition can be found here: https://github.com/smokedlinq/ConsoleHost/blob/master/.vsts-ci.yml
